### ISSUE TITLE
DiskPageStore is occuring once every 1-5 seconds

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#476]
```
11 Aug 2016 19:22:00,993 ERROR             DiskPageStore - Failed to make directory /usr/share/tomcat/work/Catalina/localhost/_/WicketWebsite-filestore/1408/8491/063840
11 Aug 2016 19:22:00,993 ERROR             DiskPageStore - Error flushing page
java.lang.RuntimeException: java.io.FileNotFoundException: /usr/share/tomcat/work/Catalina/localhost/_/WicketWebsite-filestore/1408/8491/063840531CC55346A7413310F99288E
        at org.apache.wicket.protocol.http.pagestore.FileChannelPool.newFileChannel(FileChannelPool.java:103)
        at org.apache.wicket.protocol.http.pagestore.FileChannelPool.getFileChannel(FileChannelPool.java:170)
        at org.apache.wicket.protocol.http.pagestore.DiskPageStore$SessionEntry.savePage(DiskPageStore.java:241)
        at org.apache.wicket.protocol.http.pagestore.DiskPageStore.flushPagesToSaveList(DiskPageStore.java:924)
        at org.apache.wicket.protocol.http.pagestore.DiskPageStore$PageSavingThread.run(DiskPageStore.java:996)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /usr/share/tomcat/work/Catalina/localhost/_/WicketWebsite-filestore/1408/8491/063840531CC55346A7413310F99288E8/pm-null (No suc
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.apache.wicket.protocol.http.pagestore.FileChannelPool.newFileChannel(FileChannelPool.java:98)
        ... 5 more
```

I'm investigating now.

**Comment by mattpen** [comment]
This appears to have been caused by low disk space on /var.  Mark Morlino and reduced the verbosity of /var/log/messages and added additional disk space.  Afterwards, the DiskPageStore errors discontinued, but I'll leave this open to keep an eye on it for the next few days.

**Comment by mattpen** [comment]
This error has not recurred.  Closing.
